// <auto-generated />
namespace IdentitySample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CustomProperties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomProperties));
        
        string IMigrationMetadata.Id
        {
            get { return "201605091221179_CustomProperties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
